name: Iraq Motors Collector

on:
  workflow_dispatch:

  schedule:
    - cron: "*/15 * * * *"

permissions:
  contents: write

jobs:
  collector:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install requests

      - name: Run Instagram Collector
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          APIFY_TOKEN: ${{ secrets.APIFY_TOKEN }}
        run: |
          python collector.py

      - name: Save seen_posts.json back to repo
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update seen_posts.json [skip ci]"
          file_pattern: seen_posts.json
